### ISSUE TITLE
[Tracking Issue] Improve CPU backend support without CUDA

### ISSUE THREAD

**Issue by LDY1998** [hidet-org/hidet#187]
This is a tracking issue for adding CPU compilation without CUDA:
- [x] Refactor codegen to separate GPU/CPU code generation 
        #176
- [x] Refactor Storage api to use `libc` for memory management instead of CUDA Host
        #189 
- [ ] Add test workflow in cpu-only enivironment

**Comment by SpringWave1** [comment]
Hi, when will the CPU version be available？ Looking forward to it.

**Comment by yaoyaoding** [comment]
Hi @SpringWave1, you can try it even now.
```python
a = hidet.randn([3, 4])
b = hidet.randn([4, 3])
c = a @ b
```
Hidet will generate the matrix multiplication kernel and run it with CPU. 
However, now our auto-scheduler only generates kernel that uses a single thread, and there is not efficient matmul schedule template. We are still working on these. The good support might come in the end of this year.

**Comment by vadiklyutiy** [comment]
CPU is not main target right now
